export  
const DEVELOPMENT_SKILLS = [
  {
    id: 1,
    name: 'HTML5',
    value: 100,
    message: 'Expert - Semantic HTML mastery',
    category: 'core',
  },
  {
    id: 2,
    name: 'CSS3',
    value: 100,
    message: 'Expert - Modern CSS & animations',
    category: 'core',
  },
  {
    id: 3,
    name: 'Bootstrap',
    value: 100,
    message: 'Expert - Rapid UI development',
    category: 'framework',
  },
  {
    id: 4,
    name: 'Tailwind CSS',
    value: 100,
    message: 'Expert - Utility-first approach',
    category: 'framework',
  },
  {
    id: 5,
    name: 'JavaScript',
    value: 90,
    message: 'Expert - ES6+ & async programming',
    category: 'core',
  },
  {
    id: 6,
    name: 'React.js',
    value: 90,
    message: 'Expert - Component architecture & hooks',
    category: 'library',
  },
  {
    id: 7,
    name: 'Next.js',
    value: 50,
    message: 'Learning - SSR & SSG patterns',
    category: 'framework',
  },
  {
    id: 8,
    name: 'TypeScript',
    value: 40,
    message: 'Learning - Type-safe development',
    category: 'language',
  },
  {
    id: 9,
    name: 'Redux',
    value: 70,
    message: 'Comfortable - State management',
    category: 'library',
  },
  {
    id: 10,
    name: 'Express.js',
    value: 50,
    message: 'Comfortable - REST API development',
    category: 'backend',
  },
  {
    id: 11,
    name: 'MongoDB',
    value: 50,
    message: 'Comfortable - NoSQL databases',
    category: 'backend',
  },
];